/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package altelierSwings.vue;

import atelierswings.entity.Reservation;
import atelierswings.service.ReservationService;
import java.util.List;

/**
 *
 * @author formation
 */
public class JPanelListeReservation extends javax.swing.JPanel {

    /**
     * Creates new form JPanelListeReservation
     */
    public JPanelListeReservation() {
        initComponents();
        ReservationService service = new ReservationService();
        List<Reservation> reservations = service.listerReservation();
        TableModelReservation model = new TableModelReservation(reservations);
        this.jTReservation.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jBAjout = new javax.swing.JButton();
        jBModifier = new javax.swing.JButton();
        jBSuppr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTReservation = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jBAjout.setText("Ajouter");
        jBAjout.setFocusable(false);
        jBAjout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBAjout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBAjout);

        jBModifier.setText("Modifier");
        jBModifier.setFocusable(false);
        jBModifier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBModifier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModifierActionPerformed(evt);
            }
        });
        jToolBar1.add(jBModifier);

        jBSuppr.setText("Supprimer");
        jBSuppr.setFocusable(false);
        jBSuppr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSuppr.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBSuppr);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jTReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTReservation);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jBModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModifierActionPerformed
        Long id =(Long) jTReservation.getModel().getValueAt(jTReservation.getSelectedRow(), 0);
        ReservationService service = new ReservationService();
        Reservation res = service.selectReservation(id);
        
        JPanelPrincipal parent = (JPanelPrincipal) this.getParent();
        
        parent.remplacecomposantCentral(new JPanelModifReservation(res));
        
        
    }//GEN-LAST:event_jBModifierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAjout;
    private javax.swing.JButton jBModifier;
    private javax.swing.JButton jBSuppr;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTReservation;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
