/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package altelierSwings.vue;

import atelierswings.entity.Reservation;
import atelierswings.service.ReservationService;
import java.util.List;

/**
 *
 * @author formation
 */
public class JPanelReservationsListe extends javax.swing.JPanel {

    /**
     * Creates new form JPanelReservationsListe
     */
    public JPanelReservationsListe() {
        initComponents();
        ReservationService res = new ReservationService();
        List<Reservation>reservations =res.listerReservation();
        TableModelReservation model = new TableModelReservation(reservations);
        this.jTableReservation.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        jBAjouter = new javax.swing.JButton();
        jBModifier = new javax.swing.JButton();
        jBSupprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReservation = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jToolBar2.setRollover(true);

        jBAjouter.setText("Ajouter");
        jBAjouter.setFocusable(false);
        jBAjouter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBAjouter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAjouterActionPerformed(evt);
            }
        });
        jToolBar2.add(jBAjouter);

        jBModifier.setText("Modifier");
        jBModifier.setFocusable(false);
        jBModifier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBModifier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModifierActionPerformed(evt);
            }
        });
        jToolBar2.add(jBModifier);

        jBSupprimer.setText("Supprimer");
        jBSupprimer.setFocusable(false);
        jBSupprimer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSupprimer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSupprimerActionPerformed(evt);
            }
        });
        jToolBar2.add(jBSupprimer);

        add(jToolBar2, java.awt.BorderLayout.PAGE_START);

        jTableReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableReservation);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jBAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAjouterActionPerformed
        JPanelPrincipal parent = (JPanelPrincipal) this.getParent();

        parent.remplacecomposantCentral(new JPanelReservation());
    }//GEN-LAST:event_jBAjouterActionPerformed

    private void jBModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModifierActionPerformed
        long id = (long)this.jTableReservation.getModel().getValueAt(this.jTableReservation.getSelectedRow(), 0);
        ReservationService service = new ReservationService();
        Reservation res = service.selectReservation(id);
        JPanelPrincipal parent = (JPanelPrincipal) this.getParent();
        parent.remplacecomposantCentral(new JPanelModifReservation(res));
    }//GEN-LAST:event_jBModifierActionPerformed

    private void jBSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSupprimerActionPerformed
        long row = (long) this.jTableReservation.getModel().getValueAt(this.jTableReservation.getSelectedRow(), 0);
        ReservationService service = new ReservationService();
        service.supprimerReservation(row);
        JPanelPrincipal parent = (JPanelPrincipal) this.getParent();
        parent.remplacecomposantCentral(new JPanelReservationsListe());
    }//GEN-LAST:event_jBSupprimerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAjouter;
    private javax.swing.JButton jBModifier;
    private javax.swing.JButton jBSupprimer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableReservation;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
