/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package altelierSwings.vue;

import atelierswings.entity.Chambre;
import atelierswings.entity.Client;
import atelierswings.entity.Reservation;
import atelierswings.service.ChambreService;
import atelierswings.service.ClientService;
import atelierswings.service.ReservationService;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author formation
 */
public class JPanelModifReservation extends javax.swing.JPanel {

    /**
     * Creates new form JPanelModifReservation
     */
    private Reservation reservation;

    public JPanelModifReservation() {
        initComponents();
        ComboBoxModelClient cBClient = new ComboBoxModelClient(new ClientService().listerClient());
        this.jCBClient.setModel(cBClient);
        ComboBoxModelChambre cbChambre = new ComboBoxModelChambre(new ChambreService().listerChambre());
        this.jCBChambre.setModel(cbChambre);
    }
    
    public JPanelModifReservation(Reservation reservation) {
        initComponents();
        this.reservation = reservation;
        ComboBoxModelClient cBClient = new ComboBoxModelClient(new ClientService().listerClient());
        this.jCBClient.setModel(cBClient);
        ComboBoxModelChambre cbChambre = new ComboBoxModelChambre(new ChambreService().listerChambre());
        this.jCBChambre.setModel(cbChambre);
        this.jFtfDateDebut.setValue(reservation.getDateDebut());
        this.jFtfDateFin.setValue(reservation.getDateFin());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBClient = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jCBChambre = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBModifier = new javax.swing.JButton();
        jFtfDateDebut = new javax.swing.JFormattedTextField();
        jFtfDateFin = new javax.swing.JFormattedTextField();

        setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modifier Réservations");

        jLabel2.setText("Client");

        jCBClient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Chambre");

        jCBChambre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Date de début");

        jLabel5.setText("Date de fin");

        jBModifier.setText("Modifier");
        jBModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModifierActionPerformed(evt);
            }
        });

        jFtfDateDebut.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jFtfDateFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(jCBClient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBChambre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jBModifier)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFtfDateDebut))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFtfDateFin))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCBClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCBChambre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jFtfDateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jFtfDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(jBModifier)
                .addGap(0, 74, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModifierActionPerformed
        Reservation reservation = this.reservation;
        int index = this.jCBClient.getSelectedIndex();
       Client cli = ((ComboBoxModelClient)this.jCBClient.getModel()).getListeClients().get(index);
       cli.getReservations().add(reservation);
       reservation.setClient(cli);
       int index2 = this.jCBChambre.getSelectedIndex();
        Chambre ch = ((ComboBoxModelChambre) this.jCBChambre.getModel()).getListeChambres().get(index2);
        ch.getReservations().add(reservation);
        List<Chambre> chambres = new ArrayList<>();
        chambres.add(ch);
        reservation.setChambres(chambres);
        
        reservation.setDateDebut((Date) this.jFtfDateDebut.getValue());
        reservation.setDateFin((Date) this.jFtfDateFin.getValue());
       ReservationService resService = new ReservationService();
       
        
        resService.modifierReservation(reservation);
        JPanelPrincipal parent = (JPanelPrincipal) this.getParent();
        parent.remplacecomposantCentral(new JPanelReservationsListe());
        
    }//GEN-LAST:event_jBModifierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBModifier;
    private javax.swing.JComboBox<String> jCBChambre;
    private javax.swing.JComboBox<String> jCBClient;
    private javax.swing.JFormattedTextField jFtfDateDebut;
    private javax.swing.JFormattedTextField jFtfDateFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
